export const personSchema = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "Davis Lapenta",
  alternateName: [
    "Davis Junior Laviera Lapenta",
    "Davis Laviera",
    "Davis Junior Laviera",
    "Davis Junior Lapenta",
  ],
  jobTitle: "Front-End Developer",
  description:
    "Desarrollador front-end con más de 5 años de experiencia en React, Next.js y TypeScript. Especializado en design systems, componentes reutilizables y UI/UX accesibles.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://portfolio-three-taupe-12.vercel.app",
  email: "davislapenta@gmail.com",
  sameAs: ["https://linkedin.com/in/davis-laviera/"],
  knowsAbout: [
    "React.js",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "React Native",
    "Angular",
    "Design Systems",
    "UI/UX",
    "Accessibility",
    "Jest",
    "React Testing Library",
    "Storybook",
    "Node.js",
    "Express",
    "Supabase",
    "Stripe",
    "Mercado Pago",
    "Shopify",
    "Google Apps Script",
    "Zustand",
    "TanStack Query",
    "React Hook Form",
    "Clean Architecture",
  ],
  alumniOf: [
    {
      "@type": "EducationalOrganization",
      name: "C.E.T.I.A",
      description: "Diseño y Programación de Páginas Web",
    },
    {
      "@type": "EducationalOrganization",
      name: "UTN",
      description: "Curso intensivo Angular y Drupal",
    },
  ],
  worksFor: [
    {
      "@type": "Organization",
      name: "Nonconformist",
      startDate: "2024-10",
    },
  ],
} as const;
