export const personSchema = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "Davis Lapenta",
  alternateName: [
    "Davis Junior Laviera Lapenta",
    "Davis Laviera",
    "Davis Junior Laviera",
    "Davis Junior Lapenta",
  ],
  jobTitle: "Front-End Developer",
  description:
    "Desarrollador front-end con más de 5 años de experiencia en React, Next.js y TypeScript. Especializado en design systems, componentes reutilizables y UI/UX accesibles. Participación en el Design System Obelisco del Gobierno de la Ciudad de Buenos Aires. Experiencia también en proyectos freelance: e-commerce sobre Shopify y sitios en Next.js con integración de pagos y automatizaciones.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://portfolio-three-taupe-12.vercel.app",
  email: "davislapenta@gmail.com",
  sameAs: ["https://linkedin.com/in/davis-laviera/"],
  knowsAbout: [
    "React.js",
    "Next.js",
    "React Native",
    "Angular",
    "TypeScript",
    "JavaScript",
    "HTML5",
    "CSS3",
    "SASS",
    "CSS Modules",
    "Context API",
    "Zustand",
    "Jotai",
    "TanStack Query",
    "React Hook Form",
    "Custom Hooks",
    "Node.js",
    "Express",
    "APIs REST",
    "Clean Architecture",
    "Supabase",
    "Stripe",
    "Mercado Pago",
    "Prismic",
    "Shopify",
    "Google Apps Script",
    "Design Systems",
    "UI/UX",
    "Accessibility (WCAG)",
    "Bootstrap",
    "TailwindCSS",
    "Material UI",
    "Chakra UI",
    "Figma",
    "Vite",
    "Webpack",
    "Git",
    "GitHub Actions",
    "CI/CD",
    "Vercel",
    "Expo",
    "Jest",
    "React Testing Library",
    "Storybook",
    "Firebase",
  ],
  alumniOf: [
    {
      "@type": "EducationalOrganization",
      name: "C.E.T.I.A",
      description: "Diseño y Programación de Páginas Web",
    },
    {
      "@type": "EducationalOrganization",
      name: "UTN",
      description: "Curso intensivo Angular y Drupal",
    },
  ],
  worksFor: [
    {
      "@type": "Organization",
      name: "Nonconformist",
      description:
        "Desarrollo front-end para Banco Macro: Component Design System (CDS) en React, React Native y Angular 20",
      startDate: "2024-10",
    },
    {
      "@type": "Organization",
      name: "GCBA - Secretaría de Innovación y Transformación Digital",
      description:
        "Desarrollo del Design System Obelisco del Gobierno de la Ciudad de Buenos Aires",
      startDate: "2022-07",
      endDate: "2024-10",
    },
    {
      "@type": "Organization",
      name: "Dev Queens",
      description: "Desarrollo front-end de sitios web responsive",
      startDate: "2020-02",
      endDate: "2022-07",
    },
  ],
} as const;
